version: '3'
services:
#mssql docker
  eturistickaagencija-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ASas.,12
      - MSSQL_PID=Developer
    ports:
      - 1403:1433
    networks:
      - eturistickaagencijanet

  eturistickaagencija-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=eturistickaagencija-sql,1433;Database=TuristickaAgencija;User=sa;Password=ASas.,12;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5011:5011
    networks:
      - eturistickaagencijanet
    links:
      - eturistickaagencija-sql
    depends_on:
      - eturistickaagencija-sql
      
networks:
  eturistickaagencijanet:
    driver: bridge      