version: '3'
services:
#mssql docker
  etourist-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - etouristnet

  etourist-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eTourist=Server=etourist-sql,1433;Database=eTourist1TMP;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:5050
    networks:
      - etouristnet
    links:
      - etourist-sql
    depends_on:
      - etourist-sql
      
networks:
  etouristnet:
    driver: bridge      